using System.Collections.Generic;
using System.Text.RegularExpressions;
using MimeKit;
using System.IO;
using System.Collections;

namespace PoshMailKit
{
    internal static class MailAttachments
    {
        internal static Regex pathPattern = new Regex(@"^[a-zA-Z]:");

        internal static List<string> ParseAttachments(string path, string[] attachments)
        {
            List<string> fileList = new List<string>();

            foreach (string attachment in attachments)
            {
                string fileName = GetFullPathName(path, attachment);

                if (File.Exists(fileName))
                {
                    fileList.Add(fileName);
                    continue;
                }

                throw new FileNotFoundException($"Could not find file '{fileName}'");
            }

            return fileList;
        }

        internal static List<MimePart> ParseInlineAttachments(string path, Hashtable attachments)
        {
            List<MimePart> fileMimePartList = new List<MimePart>();

            foreach (string lable in attachments.Keys)
            {
                string fileName = GetFullPathName(path, (string)attachments[lable]);

                if (File.Exists(fileName))
                {
                    fileMimePartList.Add( GetFileMimePart(lable, fileName) );
                    continue;
                }

                throw new FileNotFoundException($"Could not find file '{fileName}'");
            }

            return fileMimePartList;
        }

        private static string GetFullPathName(string path, string attachment)
        {
            if (!pathPattern.IsMatch(attachment))
                return Path.GetFullPath($"{path}\\{attachment}");
            else
                return attachment;
        }

        private static Dictionary<string, ContentType> mimeMappings = new Dictionary<string, ContentType>
        {
            { ".323",         new ContentType("text",        "h323")                                                          },
            { ".aaf",         new ContentType("application", "octet-stream")                                                  },
            { ".aca",         new ContentType("application", "octet-stream")                                                  },
            { ".accdb",       new ContentType("application", "msaccess")                                                      },
            { ".accde",       new ContentType("application", "msaccess")                                                      },
            { ".accdt",       new ContentType("application", "msaccess")                                                      },
            { ".acx",         new ContentType("application", "internet-property-stream")                                      },
            { ".afm",         new ContentType("application", "octet-stream")                                                  },
            { ".ai",          new ContentType("application", "postscript")                                                    },
            { ".aif",         new ContentType("audio",       "x-aiff")                                                        },
            { ".aifc",        new ContentType("audio",       "aiff")                                                          },
            { ".aiff",        new ContentType("audio",       "aiff")                                                          },
            { ".application", new ContentType("application", "x-ms-application")                                              },
            { ".art",         new ContentType("image",       "x-jg")                                                          },
            { ".asd",         new ContentType("application", "octet-stream")                                                  },
            { ".asf",         new ContentType("video",       "x-ms-asf")                                                      },
            { ".asi",         new ContentType("application", "octet-stream")                                                  },
            { ".asm",         new ContentType("text",        "plain")                                                         },
            { ".asr",         new ContentType("video",       "x-ms-asf")                                                      },
            { ".asx",         new ContentType("video",       "x-ms-asf")                                                      },
            { ".atom",        new ContentType("application", "atom+xml")                                                      },
            { ".au",          new ContentType("audio",       "basic")                                                         },
            { ".avi",         new ContentType("video",       "x-msvideo")                                                     },
            { ".axs",         new ContentType("application", "olescript")                                                     },
            { ".bas",         new ContentType("text",        "plain")                                                         },
            { ".bcpio",       new ContentType("application", "x-bcpio")                                                       },
            { ".bin",         new ContentType("application", "octet-stream")                                                  },
            { ".bmp",         new ContentType("image",       "bmp")                                                           },
            { ".c",           new ContentType("text",        "plain")                                                         },
            { ".cab",         new ContentType("application", "octet-stream")                                                  },
            { ".calx",        new ContentType("application", "vnd.ms-office.calx")                                            },
            { ".cat",         new ContentType("application", "vnd.ms-pki.seccat")                                             },
            { ".cdf",         new ContentType("application", "x-cdf")                                                         },
            { ".chm",         new ContentType("application", "octet-stream")                                                  },
            { ".class",       new ContentType("application", "x-java-applet")                                                 },
            { ".clp",         new ContentType("application", "x-msclip")                                                      },
            { ".cmx",         new ContentType("image",       "x-cmx")                                                         },
            { ".cnf",         new ContentType("text",        "plain")                                                         },
            { ".cod",         new ContentType("image",       "cis-cod")                                                       },
            { ".cpio",        new ContentType("application", "x-cpio")                                                        },
            { ".cpp",         new ContentType("text",        "plain")                                                         },
            { ".crd",         new ContentType("application", "x-mscardfile")                                                  },
            { ".crl",         new ContentType("application", "pkix-crl")                                                      },
            { ".crt",         new ContentType("application", "x-x509-ca-cert")                                                },
            { ".csh",         new ContentType("application", "x-csh")                                                         },
            { ".css",         new ContentType("text",        "css")                                                           },
            { ".csv",         new ContentType("application", "octet-stream")                                                  },
            { ".cur",         new ContentType("application", "octet-stream")                                                  },
            { ".dcr",         new ContentType("application", "x-director")                                                    },
            { ".deploy",      new ContentType("application", "octet-stream")                                                  },
            { ".der",         new ContentType("application", "x-x509-ca-cert")                                                },
            { ".dib",         new ContentType("image",       "bmp")                                                           },
            { ".dir",         new ContentType("application", "x-director")                                                    },
            { ".disco",       new ContentType("text",        "xml")                                                           },
            { ".dll",         new ContentType("application", "x-msdownload")                                                  },
            { ".dll.config",  new ContentType("text",        "xml")                                                           },
            { ".dlm",         new ContentType("text",        "dlm")                                                           },
            { ".doc",         new ContentType("application", "msword")                                                        },
            { ".docm",        new ContentType("application", "vnd.ms-word.document.macroEnabled.12")                          },
            { ".docx",        new ContentType("application", "vnd.openxmlformats-officedocument.wordprocessingml.document")   },
            { ".dot",         new ContentType("application", "msword")                                                        },
            { ".dotm",        new ContentType("application", "vnd.ms-word.template.macroEnabled.12")                          },
            { ".dotx",        new ContentType("application", "vnd.openxmlformats-officedocument.wordprocessingml.template")   },
            { ".dsp",         new ContentType("application", "octet-stream")                                                  },
            { ".dtd",         new ContentType("text",        "xml")                                                           },
            { ".dvi",         new ContentType("application", "x-dvi")                                                         },
            { ".dwf",         new ContentType("drawing",     "x-dwf")                                                         },
            { ".dwp",         new ContentType("application", "octet-stream")                                                  },
            { ".dxr",         new ContentType("application", "x-director")                                                    },
            { ".eml",         new ContentType("message",     "rfc822")                                                        },
            { ".emz",         new ContentType("application", "octet-stream")                                                  },
            { ".eot",         new ContentType("application", "octet-stream")                                                  },
            { ".eps",         new ContentType("application", "postscript")                                                    },
            { ".etx",         new ContentType("text",        "x-setext")                                                      },
            { ".evy",         new ContentType("application", "envoy")                                                         },
            { ".exe",         new ContentType("application", "octet-stream")                                                  },
            { ".exe.config",  new ContentType("text",        "xml")                                                           },
            { ".fdf",         new ContentType("application", "vnd.fdf")                                                       },
            { ".fif",         new ContentType("application", "fractals")                                                      },
            { ".fla",         new ContentType("application", "octet-stream")                                                  },
            { ".flr",         new ContentType("x-world",     "x-vrml")                                                        },
            { ".flv",         new ContentType("video",       "x-flv")                                                         },
            { ".gif",         new ContentType("image",       "gif")                                                           },
            { ".gtar",        new ContentType("application", "x-gtar")                                                        },
            { ".gz",          new ContentType("application", "x-gzip")                                                        },
            { ".h",           new ContentType("text",        "plain")                                                         },
            { ".hdf",         new ContentType("application", "x-hdf")                                                         },
            { ".hdml",        new ContentType("text",        "x-hdml")                                                        },
            { ".hhc",         new ContentType("application", "x-oleobject")                                                   },
            { ".hhk",         new ContentType("application", "octet-stream")                                                  },
            { ".hhp",         new ContentType("application", "octet-stream")                                                  },
            { ".hlp",         new ContentType("application", "winhlp")                                                        },
            { ".hqx",         new ContentType("application", "mac-binhex40")                                                  },
            { ".hta",         new ContentType("application", "hta")                                                           },
            { ".htc",         new ContentType("text",        "x-component")                                                   },
            { ".htm",         new ContentType("text",        "html")                                                          },
            { ".html",        new ContentType("text",        "html")                                                          },
            { ".htt",         new ContentType("text",        "webviewhtml")                                                   },
            { ".hxt",         new ContentType("text",        "html")                                                          },
            { ".ico",         new ContentType("image",       "x-icon")                                                        },
            { ".ics",         new ContentType("application", "octet-stream")                                                  },
            { ".ief",         new ContentType("image",       "ief")                                                           },
            { ".iii",         new ContentType("application", "x-iphone")                                                      },
            { ".inf",         new ContentType("application", "octet-stream")                                                  },
            { ".ins",         new ContentType("application", "x-internet-signup")                                             },
            { ".isp",         new ContentType("application", "x-internet-signup")                                             },
            { ".IVF",         new ContentType("video",       "x-ivf")                                                         },
            { ".jar",         new ContentType("application", "java-archive")                                                  },
            { ".java",        new ContentType("application", "octet-stream")                                                  },
            { ".jck",         new ContentType("application", "liquidmotion")                                                  },
            { ".jcz",         new ContentType("application", "liquidmotion")                                                  },
            { ".jfif",        new ContentType("image",       "pjpeg")                                                         },
            { ".jpb",         new ContentType("application", "octet-stream")                                                  },
            { ".jpe",         new ContentType("image",       "jpeg")                                                          },
            { ".jpeg",        new ContentType("image",       "jpeg")                                                          },
            { ".jpg",         new ContentType("image",       "jpeg")                                                          },
            { ".js",          new ContentType("application", "x-javascript")                                                  },
            { ".jsx",         new ContentType("text",        "jscript")                                                       },
            { ".latex",       new ContentType("application", "x-latex")                                                       },
            { ".lit",         new ContentType("application", "x-ms-reader")                                                   },
            { ".lpk",         new ContentType("application", "octet-stream")                                                  },
            { ".lsf",         new ContentType("video",       "x-la-asf")                                                      },
            { ".lsx",         new ContentType("video",       "x-la-asf")                                                      },
            { ".lzh",         new ContentType("application", "octet-stream")                                                  },
            { ".m13",         new ContentType("application", "x-msmediaview")                                                 },
            { ".m14",         new ContentType("application", "x-msmediaview")                                                 },
            { ".m1v",         new ContentType("video",       "mpeg")                                                          },
            { ".m3u",         new ContentType("audio",       "x-mpegurl")                                                     },
            { ".man",         new ContentType("application", "x-troff-man")                                                   },
            { ".manifest",    new ContentType("application", "x-ms-manifest")                                                 },
            { ".map",         new ContentType("text",        "plain")                                                         },
            { ".mdb",         new ContentType("application", "x-msaccess")                                                    },
            { ".mdp",         new ContentType("application", "octet-stream")                                                  },
            { ".me",          new ContentType("application", "x-troff-me")                                                    },
            { ".mht",         new ContentType("message",     "rfc822")                                                        },
            { ".mhtml",       new ContentType("message",     "rfc822")                                                        },
            { ".mid",         new ContentType("audio",       "mid")                                                           },
            { ".midi",        new ContentType("audio",       "mid")                                                           },
            { ".mix",         new ContentType("application", "octet-stream")                                                  },
            { ".mmf",         new ContentType("application", "x-smaf")                                                        },
            { ".mno",         new ContentType("text",        "xml")                                                           },
            { ".mny",         new ContentType("application", "x-msmoney")                                                     },
            { ".mov",         new ContentType("video",       "quicktime")                                                     },
            { ".movie",       new ContentType("video",       "x-sgi-movie")                                                   },
            { ".mp2",         new ContentType("video",       "mpeg")                                                          },
            { ".mp3",         new ContentType("audio",       "mpeg")                                                          },
            { ".mpa",         new ContentType("video",       "mpeg")                                                          },
            { ".mpe",         new ContentType("video",       "mpeg")                                                          },
            { ".mpeg",        new ContentType("video",       "mpeg")                                                          },
            { ".mpg",         new ContentType("video",       "mpeg")                                                          },
            { ".mpp",         new ContentType("application", "vnd.ms-project")                                                },
            { ".mpv2",        new ContentType("video",       "mpeg")                                                          },
            { ".ms",          new ContentType("application", "x-troff-ms")                                                    },
            { ".msi",         new ContentType("application", "octet-stream")                                                  },
            { ".mso",         new ContentType("application", "octet-stream")                                                  },
            { ".mvb",         new ContentType("application", "x-msmediaview")                                                 },
            { ".mvc",         new ContentType("application", "x-miva-compiled")                                               },
            { ".nc",          new ContentType("application", "x-netcdf")                                                      },
            { ".nsc",         new ContentType("video",       "x-ms-asf")                                                      },
            { ".nws",         new ContentType("message",     "rfc822")                                                        },
            { ".ocx",         new ContentType("application", "octet-stream")                                                  },
            { ".oda",         new ContentType("application", "oda")                                                           },
            { ".odc",         new ContentType("text",        "x-ms-odc")                                                      },
            { ".ods",         new ContentType("application", "oleobject")                                                     },
            { ".one",         new ContentType("application", "onenote")                                                       },
            { ".onea",        new ContentType("application", "onenote")                                                       },
            { ".onetoc",      new ContentType("application", "onenote")                                                       },
            { ".onetoc2",     new ContentType("application", "onenote")                                                       },
            { ".onetmp",      new ContentType("application", "onenote")                                                       },
            { ".onepkg",      new ContentType("application", "onenote")                                                       },
            { ".osdx",        new ContentType("application", "opensearchdescription+xml")                                     },
            { ".p10",         new ContentType("application", "pkcs10")                                                        },
            { ".p12",         new ContentType("application", "x-pkcs12")                                                      },
            { ".p7b",         new ContentType("application", "x-pkcs7-certificates")                                          },
            { ".p7c",         new ContentType("application", "pkcs7-mime")                                                    },
            { ".p7m",         new ContentType("application", "pkcs7-mime")                                                    },
            { ".p7r",         new ContentType("application", "x-pkcs7-certreqresp")                                           },
            { ".p7s",         new ContentType("application", "pkcs7-signature")                                               },
            { ".pbm",         new ContentType("image",       "x-portable-bitmap")                                             },
            { ".pcx",         new ContentType("application", "octet-stream")                                                  },
            { ".pcz",         new ContentType("application", "octet-stream")                                                  },
            { ".pdf",         new ContentType("application", "pdf")                                                           },
            { ".pfb",         new ContentType("application", "octet-stream")                                                  },
            { ".pfm",         new ContentType("application", "octet-stream")                                                  },
            { ".pfx",         new ContentType("application", "x-pkcs12")                                                      },
            { ".pgm",         new ContentType("image",       "x-portable-graymap")                                            },
            { ".pko",         new ContentType("application", "vnd.ms-pki.pko")                                                },
            { ".pma",         new ContentType("application", "x-perfmon")                                                     },
            { ".pmc",         new ContentType("application", "x-perfmon")                                                     },
            { ".pml",         new ContentType("application", "x-perfmon")                                                     },
            { ".pmr",         new ContentType("application", "x-perfmon")                                                     },
            { ".pmw",         new ContentType("application", "x-perfmon")                                                     },
            { ".png",         new ContentType("image",       "png")                                                           },
            { ".pnm",         new ContentType("image",       "x-portable-anymap")                                             },
            { ".pnz",         new ContentType("image",       "png")                                                           },
            { ".pot",         new ContentType("application", "vnd.ms-powerpoint")                                             },
            { ".potm",        new ContentType("application", "vnd.ms-powerpoint.template.macroEnabled.12")                    },
            { ".potx",        new ContentType("application", "vnd.openxmlformats-officedocument.presentationml.template")     },
            { ".ppam",        new ContentType("application", "vnd.ms-powerpoint.addin.macroEnabled.12")                       },
            { ".ppm",         new ContentType("image",       "x-portable-pixmap")                                             },
            { ".pps",         new ContentType("application", "vnd.ms-powerpoint")                                             },
            { ".ppsm",        new ContentType("application", "vnd.ms-powerpoint.slideshow.macroEnabled.12")                   },
            { ".ppsx",        new ContentType("application", "vnd.openxmlformats-officedocument.presentationml.slideshow")    },
            { ".ppt",         new ContentType("application", "vnd.ms-powerpoint")                                             },
            { ".pptm",        new ContentType("application", "vnd.ms-powerpoint.presentation.macroEnabled.12")                },
            { ".pptx",        new ContentType("application", "vnd.openxmlformats-officedocument.presentationml.presentation") },
            { ".prf",         new ContentType("application", "pics-rules")                                                    },
            { ".prm",         new ContentType("application", "octet-stream")                                                  },
            { ".prx",         new ContentType("application", "octet-stream")                                                  },
            { ".ps",          new ContentType("application", "postscript")                                                    },
            { ".psd",         new ContentType("application", "octet-stream")                                                  },
            { ".psm",         new ContentType("application", "octet-stream")                                                  },
            { ".psp",         new ContentType("application", "octet-stream")                                                  },
            { ".pub",         new ContentType("application", "x-mspublisher")                                                 },
            { ".qt",          new ContentType("video",       "quicktime")                                                     },
            { ".qtl",         new ContentType("application", "x-quicktimeplayer")                                             },
            { ".qxd",         new ContentType("application", "octet-stream")                                                  },
            { ".ra",          new ContentType("audio",       "x-pn-realaudio")                                                },
            { ".ram",         new ContentType("audio",       "x-pn-realaudio")                                                },
            { ".rar",         new ContentType("application", "octet-stream")                                                  },
            { ".ras",         new ContentType("image",       "x-cmu-raster")                                                  },
            { ".rf",          new ContentType("image",       "vnd.rn-realflash")                                              },
            { ".rgb",         new ContentType("image",       "x-rgb")                                                         },
            { ".rm",          new ContentType("application", "vnd.rn-realmedia")                                              },
            { ".rmi",         new ContentType("audio",       "mid")                                                           },
            { ".roff",        new ContentType("application", "x-troff")                                                       },
            { ".rpm",         new ContentType("audio",       "x-pn-realaudio-plugin")                                         },
            { ".rtf",         new ContentType("application", "rtf")                                                           },
            { ".rtx",         new ContentType("text",        "richtext")                                                      },
            { ".scd",         new ContentType("application", "x-msschedule")                                                  },
            { ".sct",         new ContentType("text",        "scriptlet")                                                     },
            { ".sea",         new ContentType("application", "octet-stream")                                                  },
            { ".setpay",      new ContentType("application", "set-payment-initiation")                                        },
            { ".setreg",      new ContentType("application", "set-registration-initiation")                                   },
            { ".sgml",        new ContentType("text",        "sgml")                                                          },
            { ".sh",          new ContentType("application", "x-sh")                                                          },
            { ".shar",        new ContentType("application", "x-shar")                                                        },
            { ".sit",         new ContentType("application", "x-stuffit")                                                     },
            { ".sldm",        new ContentType("application", "vnd.ms-powerpoint.slide.macroEnabled.12")                       },
            { ".sldx",        new ContentType("application", "vnd.openxmlformats-officedocument.presentationml.slide")        },
            { ".smd",         new ContentType("audio",       "x-smd")                                                         },
            { ".smi",         new ContentType("application", "octet-stream")                                                  },
            { ".smx",         new ContentType("audio",       "x-smd")                                                         },
            { ".smz",         new ContentType("audio",       "x-smd")                                                         },
            { ".snd",         new ContentType("audio",       "basic")                                                         },
            { ".snp",         new ContentType("application", "octet-stream")                                                  },
            { ".spc",         new ContentType("application", "x-pkcs7-certificates")                                          },
            { ".spl",         new ContentType("application", "futuresplash")                                                  },
            { ".src",         new ContentType("application", "x-wais-source")                                                 },
            { ".ssm",         new ContentType("application", "streamingmedia")                                                },
            { ".sst",         new ContentType("application", "vnd.ms-pki.certstore")                                          },
            { ".stl",         new ContentType("application", "vnd.ms-pki.stl")                                                },
            { ".sv4cpio",     new ContentType("application", "x-sv4cpio")                                                     },
            { ".sv4crc",      new ContentType("application", "x-sv4crc")                                                      },
            { ".swf",         new ContentType("application", "x-shockwave-flash")                                             },
            { ".t",           new ContentType("application", "x-troff")                                                       },
            { ".tar",         new ContentType("application", "x-tar")                                                         },
            { ".tcl",         new ContentType("application", "x-tcl")                                                         },
            { ".tex",         new ContentType("application", "x-tex")                                                         },
            { ".texi",        new ContentType("application", "x-texinfo")                                                     },
            { ".texinfo",     new ContentType("application", "x-texinfo")                                                     },
            { ".tgz",         new ContentType("application", "x-compressed")                                                  },
            { ".thmx",        new ContentType("application", "vnd.ms-officetheme")                                            },
            { ".thn",         new ContentType("application", "octet-stream")                                                  },
            { ".tif",         new ContentType("image",       "tiff")                                                          },
            { ".tiff",        new ContentType("image",       "tiff")                                                          },
            { ".toc",         new ContentType("application", "octet-stream")                                                  },
            { ".tr",          new ContentType("application", "x-troff")                                                       },
            { ".trm",         new ContentType("application", "x-msterminal")                                                  },
            { ".tsv",         new ContentType("text",        "tab-separated-values")                                          },
            { ".ttf",         new ContentType("application", "octet-stream")                                                  },
            { ".txt",         new ContentType("text",        "plain")                                                         },
            { ".u32",         new ContentType("application", "octet-stream")                                                  },
            { ".uls",         new ContentType("text",        "iuls")                                                          },
            { ".ustar",       new ContentType("application", "x-ustar")                                                       },
            { ".vbs",         new ContentType("text",        "vbscript")                                                      },
            { ".vcf",         new ContentType("text",        "x-vcard")                                                       },
            { ".vcs",         new ContentType("text",        "plain")                                                         },
            { ".vdx",         new ContentType("application", "vnd.ms-visio.viewer")                                           },
            { ".vml",         new ContentType("text",        "xml")                                                           },
            { ".vsd",         new ContentType("application", "vnd.visio")                                                     },
            { ".vss",         new ContentType("application", "vnd.visio")                                                     },
            { ".vst",         new ContentType("application", "vnd.visio")                                                     },
            { ".vsto",        new ContentType("application", "x-ms-vsto")                                                     },
            { ".vsw",         new ContentType("application", "vnd.visio")                                                     },
            { ".vsx",         new ContentType("application", "vnd.visio")                                                     },
            { ".vtx",         new ContentType("application", "vnd.visio")                                                     },
            { ".wav",         new ContentType("audio",       "wav")                                                           },
            { ".wax",         new ContentType("audio",       "x-ms-wax")                                                      },
            { ".wbmp",        new ContentType("image",       "vnd.wap.wbmp")                                                  },
            { ".wcm",         new ContentType("application", "vnd.ms-works")                                                  },
            { ".wdb",         new ContentType("application", "vnd.ms-works")                                                  },
            { ".wks",         new ContentType("application", "vnd.ms-works")                                                  },
            { ".wm",          new ContentType("video",       "x-ms-wm")                                                       },
            { ".wma",         new ContentType("audio",       "x-ms-wma")                                                      },
            { ".wmd",         new ContentType("application", "x-ms-wmd")                                                      },
            { ".wmf",         new ContentType("application", "x-msmetafile")                                                  },
            { ".wml",         new ContentType("text",        "vnd.wap.wml")                                                   },
            { ".wmlc",        new ContentType("application", "vnd.wap.wmlc")                                                  },
            { ".wmls",        new ContentType("text",        "vnd.wap.wmlscript")                                             },
            { ".wmlsc",       new ContentType("application", "vnd.wap.wmlscriptc")                                            },
            { ".wmp",         new ContentType("video",       "x-ms-wmp")                                                      },
            { ".wmv",         new ContentType("video",       "x-ms-wmv")                                                      },
            { ".wmx",         new ContentType("video",       "x-ms-wmx")                                                      },
            { ".wmz",         new ContentType("application", "x-ms-wmz")                                                      },
            { ".wps",         new ContentType("application", "vnd.ms-works")                                                  },
            { ".wri",         new ContentType("application", "x-mswrite")                                                     },
            { ".wrl",         new ContentType("x-world",     "x-vrml")                                                        },
            { ".wrz",         new ContentType("x-world",     "x-vrml")                                                        },
            { ".wsdl",        new ContentType("text",        "xml")                                                           },
            { ".wvx",         new ContentType("video",       "x-ms-wvx")                                                      },
            { ".x",           new ContentType("application", "directx")                                                       },
            { ".xaf",         new ContentType("x-world",     "x-vrml")                                                        },
            { ".xaml",        new ContentType("application", "xaml+xml")                                                      },
            { ".xap",         new ContentType("application", "x-silverlight-app")                                             },
            { ".xbap",        new ContentType("application", "x-ms-xbap")                                                     },
            { ".xbm",         new ContentType("image",       "x-xbitmap")                                                     },
            { ".xdr",         new ContentType("text",        "plain")                                                         },
            { ".xla",         new ContentType("application", "vnd.ms-excel")                                                  },
            { ".xlam",        new ContentType("application", "vnd.ms-excel.addin.macroEnabled.12")                            },
            { ".xlc",         new ContentType("application", "vnd.ms-excel")                                                  },
            { ".xlm",         new ContentType("application", "vnd.ms-excel")                                                  },
            { ".xls",         new ContentType("application", "vnd.ms-excel")                                                  },
            { ".xlsb",        new ContentType("application", "vnd.ms-excel.sheet.binary.macroEnabled.12")                     },
            { ".xlsm",        new ContentType("application", "vnd.ms-excel.sheet.macroEnabled.12")                            },
            { ".xlsx",        new ContentType("application", "vnd.openxmlformats-officedocument.spreadsheetml.sheet")         },
            { ".xlt",         new ContentType("application", "vnd.ms-excel")                                                  },
            { ".xltm",        new ContentType("application", "vnd.ms-excel.template.macroEnabled.12")                         },
            { ".xltx",        new ContentType("application", "vnd.openxmlformats-officedocument.spreadsheetml.template")      },
            { ".xlw",         new ContentType("application", "vnd.ms-excel")                                                  },
            { ".xml",         new ContentType("text",        "xml")                                                           },
            { ".xof",         new ContentType("x-world",     "x-vrml")                                                        },
            { ".xpm",         new ContentType("image",       "x-xpixmap")                                                     },
            { ".xps",         new ContentType("application", "vnd.ms-xpsdocument")                                            },
            { ".xsd",         new ContentType("text",        "xml")                                                           },
            { ".xsf",         new ContentType("text",        "xml")                                                           },
            { ".xsl",         new ContentType("text",        "xml")                                                           },
            { ".xslt",        new ContentType("text",        "xml")                                                           },
            { ".xsn",         new ContentType("application", "octet-stream")                                                  },
            { ".xtp",         new ContentType("application", "octet-stream")                                                  },
            { ".xwd",         new ContentType("image",       "x-xwindowdump")                                                 },
            { ".z",           new ContentType("application", "x-compress")                                                    },
            { ".zip",         new ContentType("application", "x-zip-compressed")                                              },
        };
        private static MimePart GetFileMimePart(string lable, string fileName)
        {
            Stream fileStream = File.OpenRead(fileName);
            string ext = Path.GetExtension(fileName);
            return new MimePart(mimeMappings[ext])
            {
                ContentId = lable,
                Content = new MimeContent(fileStream),
            };
        }
    }
}
